### ISSUE TITLE
Grey out route boxes beyond the selected trip time

### ISSUE THREAD

**Issue by guytepper** [better-rail/app#128]
In the route list screen, grey out routes that are 1 hour before and 1 hour after the user selected time - unless there are no relevant trains in those times. 

If the user did not select a specific time (meaning it's searching for "now") - do not apply this effect.

**Comment by MenachemZeivald** [comment]
How should it look on a dark theme?

Btw it could be helpful to add an option to change the theme on the app

**Comment by planecore** [comment]
I think it would just be confusing. The current implementation of scrolling to the relevant times is good enough. I do believe we should implement #23 instead though.
