### ISSUE TITLE
Black screen when system language isn't supported by the app

### ISSUE THREAD

**Issue by guytepper** [better-rail/app#201]
the reported issue came from a user with Spanish system language, fixed once changed the system language to Englsih
<img src="https://user-images.githubusercontent.com/13344923/241856839-71c7576e-590a-4f05-8247-1f002661214c.jpg" alt="IMAGE 2023-05-30 11:00:42 AM" width="250" />

**Comment by MenachemZeivald** [comment]
Maybe we can fix this by setting a default language, like Hebrew or English?

**Comment by guytepper** [comment]
Hey @MenachemZeivald! the default language is set by the device locale, as can be seen in https://github.com/better-rail/app/blob/main/app/i18n/i18n.ts#L28

If you'd like to work on it, I would change the device language to something else than a language we support, and see if there's any error thrown.

It seems like we only handle the language we support, so we need to add a condition when an unsupported language is provided, we should set the app language to English.

Let me know if you'd like to tackle this issue :)  just be aware that we are near the release of the new version, so the timeline is tight and we'll need to have this done in the upcoming days
