### ISSUE TITLE
Show train delays on Apple Watch

### ISSUE THREAD

**Issue by planecore** [better-rail/app#228]
Show train delays in the routes list and in a route view like the main app:

![incoming-A4E5551E-7F4D-4DF5-AAE5-BFBEE89F772A](https://github.com/better-rail/app/assets/12946462/57e9a14d-e3a1-4acf-93a0-33827466105e)
![incoming-3F60CF3B-D735-4722-986E-60518FE552BC](https://github.com/better-rail/app/assets/12946462/d500f6f4-194e-402b-b7d9-62a563ddbfdf)

**Comment by guytepper** [comment]
@planecore how do you imagine it could be represented? both the delay itself and the updated times. screen estate is very limited here
