### ISSUE TITLE
Add ticket fares information

### ISSUE THREAD

**Issue by planecore** [better-rail/app#276]
Added in #55 and has been removed here: https://github.com/better-rail/app/commit/4f41bcb3b09f1ad9f2d0c0d7d8612bab7dfbc60e

The new fares API can be accessed via `https://israelrail.azurefd.net/taarif/api/v1/PriceEng/GetAllPrice`

**Comment by YossiSaadi** [comment]
I'll try to take it :)

**Comment by guytepper** [comment]
We decided to focus on other features for the foreseeable future
