### ISSUE TITLE
Music stops when opening

### ISSUE THREAD

**Issue by Oded2** [better-rail/app#300]
## 🐛 Bug Description:
Provide a clear and concise description of the bug encountered.

## 📷 Screenshots/Logs:
Attach any relevant screenshots, error logs, or console outputs to help identify the issue.

## 💻 Environment:
Specify the relevant environment details where the bug occurred:

**Comment by guytepper** [comment]
Hey, thanks for the report! 
Can you please fill the issue template so it'd be easier for us to reproduce?

**Comment by guytepper** [comment]
let us know if the issue presists, closing for now
