### ISSUE TITLE
Not starting ride

### ISSUE THREAD

**Issue by Oded2** [better-rail/app#301]
## 🐛 Bug Description:
I simply click on start ride and it just stays stuck loading. I've tried restarting my phone and re installing the app. 

## 🔍 Steps to Reproduce:

    1. Open app
    2. Start ride

## 📷 Screenshots/Logs:
![image](https://github.com/better-rail/app/assets/111157775/d06ac657-17ac-42b9-a5f9-4af8889a40a1)
## 💻 Environment:
Specify the relevant environment details where the bug occurred:

    Device: iPhone 13
    OS: iOS 17 public beta
    Version: Latest as of August 21 2023

**Comment by guytepper** [comment]
hey @Oded2, thanks for reporting on this! 
the server probably responded with an error, but since we're not handling errors very good at the moment it didn't show up and the loading progress remained infinitely. we'll fix it via #302 

does it happen every time you try to start a ride, or only occasionally?

**Comment by Oded2** [comment]
> hey @Oded2, thanks for reporting on this! 
> 
> the server probably responded with an error, but since we're not handling errors very good at the moment it didn't show up and the loading progress remained infinitely. we'll fix it via #302 
> 
> 
> 
> does it happen every time you try to start a ride, or only occasionally?

It only happened once so far, when I was in Haifa trying to get home.  Ever since it never happened again.

**Comment by guytepper** [comment]
okay, good to know. Since it's probably an error occured at the server level which we didn't display, I'm closing the issue for now.
