### ISSUE TITLE
Add to F-Droid

### ISSUE THREAD

**Issue by licaon-kter** [better-rail/app#327]
ref: https://f-droid.org/docs/Inclusion_Policy/

ref: https://gitlab.com/fdroid/rfp/-/issues/1731

Obstacles? non FOSS dependencies
* https://github.com/better-rail/app/blob/v2.1.0/package.json#L37-L41
* https://github.com/better-rail/app/blob/v2.1.0/package.json#L71-L72
* https://github.com/better-rail/app/blob/v2.1.0/package.json#L80
* ...maybe more?

**Comment by guytepper** [comment]
Hi, thanks for coming over here :) 

Personally I wouldn't want to maintain a separate flavor of the app for F-Droid at this time, but definitely open to collaborate if someone from the community is interested in taking on this task (looking at you @sha-265 😉)

**Comment by planecore** [comment]
As F-Droid doesn't allow apps with closed-source SDKs I'll close this issue for now. If anyone is willing to make the needed modifications please let me know!
