### ISSUE TITLE
HTML tags should be removed or formatted in urgent updates 

### ISSUE THREAD

**Issue by sha-265** [better-rail/app#337]
## 🐛 Bug Description:
HTML tags appears as preformatted text, and should formatted or removed.

## 🔍 Steps to Reproduce:

    1. Open the app with urgent updates
    2. Click the update, and see the text

## 📷 Screenshots/Logs:
![image](https://github.com/better-rail/app/assets/4103710/61a06c31-2e2b-499f-9564-8c7bef08e2a4)

![image](https://github.com/better-rail/app/assets/4103710/6f6b045c-9bfd-47f7-a518-d43bf9a54425)

## 💻 Environment:
Specify the relevant environment details where the bug occurred:

    Device: Pixel 4a
    OS: Android 13

**Comment by guytepper** [comment]
Thanks for the report, a fix is in #335 which will be merged soon
