### ISSUE TITLE
Display stops before and after stations in active route.

### ISSUE THREAD

**Issue by papaia** [better-rail/app#345]
Add an option to see the train's stops that come before and after the ride's origin and destination stations, similarly to what is possible in the official website.

Example:
![Hebrew exmaple](https://github.com/better-rail/app/assets/43409674/5696744b-5d1d-4b61-9fa3-800669c524d1)
![English example](https://github.com/better-rail/app/assets/43409674/1621fcf0-67ae-4f80-8af7-0e3c2c8b3473)

## 🧐 How to approach:
- The `Train` type would have to hold stops that occur before its origin and destination stations.
- The screen file to be edited is [`app/screens/route-details/route-details-screen.tsx`](https://github.com/better-rail/app/blob/main/app/screens/route-details/route-details-screen.tsx).

**Comment by papaia** [comment]
I am not familiar with the libraries and APIs in use, and barely even know the project itself. I'll see what I can do but it won't happen anytime soon unfortunately.

**Comment by guytepper** [comment]
We decided to focus on other features for the foreseeable future. Sorry!

**Comment by papaia** [comment]
It appears that this feature is now implemented for rides without train changes, could it be extended to ones that do have a change?

**Comment by guytepper** [comment]
@papaia we can certainly look into that. Care opening an issue that shows the problem you're seeing?
