### ISSUE TITLE
Run on MacOS with Apple Silicon

### ISSUE THREAD

**Issue by itaysk** [better-rail/app#346]
Some (most?) iOS apps can be run on MacOS with Apple Silicon: https://support.apple.com/en-il/guide/app-store/fird2c7092da/mac
For example, I can run the official Israel Railway iOS app on my mac.
However, the Better Rail app is not available on the app store for mac (even not as an iOS app).

**Comment by guytepper** [comment]
Hey, thanks for the heads up on this.
I just made the app available on macOS but it crashes on launch. We'll investigate why it's happening and update once it's resolved :)

**Comment by itaysk** [comment]
thanks for this awesome app :)

**Comment by guytepper** [comment]
Hey @itaysk, I fixed the issue. It will be available on the next major version.

If you'd like to test and provide feedback, send your Apple ID to `feedback@better-rail.co.il` and I'll invite you to our TestFlight program :)
