### ISSUE TITLE
suggestion: more options for short connections

### ISSUE THREAD

**Issue by itaysk** [better-rail/app#347]
If a ride that includes multiple trains, the app will show the combination of trains with the least wait time in between. this is good in theory but in reality, Israel Railways are late too often, and are not always reporting their delays. This means that if a connection is short (as the app prefers to minimize), there’s a good chance to miss the next train. I saw that the app already warns when a connection is short. It would be very helpful if the app would give us an option go take an earlier train to extent the connection time.
2 examples from my experience today:
1. Tel Aviv Center to Raanana West, the usual route with connection in Herzliya of 5 min. The train arrived at Herzliya a few minutes later for some reason, and it was not reported as delay in the system. the Sharon train left on time and everyone on that train missed it and had to wait 30 min for the next one.
2. I look for train from Raanana West to Tel Aviv in the morning, route via Herzliya, I see 30 min gap between departures: 08:53, 09:23, but there’s another train going to Herzliya at 09:17 that the app never shows.

This behavior is common to the official Israel Railway app, but I was hoping Better Rail can improve upon it.

my suggestion is to show all the trains leaving between the time of the search and the time of the train with shortest connection. This can be shown in the regular search results as more options, or only when viewing a route with short connection (whatever you think makes more sense)

**Comment by planecore** [comment]
Hey, thank you for the detailed suggestion! Currently we have no plans to develop a route planning engine ourselves as it'd need a lot of resources and time to make it right, so we use routes provided by the Israel Railways API. Sorry, but we appreciate bringing this idea up 🙏
