### ISSUE TITLE
Fix plural “1 minutes” delay to “1 minute”

### ISSUE THREAD

**Issue by guytepper** [better-rail/app#386]
<img src="https://private-user-images.githubusercontent.com/13344923/380418117-448c7c24-ac10-441c-b7fd-e1a8c7566252.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5NDExNDIsIm5iZiI6MTcyOTk0MDg0MiwicGF0aCI6Ii8xMzM0NDkyMy8zODA0MTgxMTctNDQ4YzdjMjQtYWMxMC00NDFjLWI3ZmQtZTFhOGM3NTY2MjUyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI2VDExMDcyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0MDhmY2U0ZDY1MTIwYjAyZjk3ZTEyM2RhNzZjNGU4MDVhZmVkODg4NDcwYzZlZWMzYTRlYTk3MjA1MjExNGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wUSQLCrHpybVC7qlOFSvETilgIZZ0evouLwhSMWcEmY" width="200" />

**Comment by planecore** [comment]
This will be merged with #381
