### ISSUE TITLE
Missing stations images

### ISSUE THREAD

**Issue by guytepper** [better-rail/app#81]
Tired of coding? Time to show off your photography skills!

## 🧐 How to approach:
- Submitted images should be added to `assets/station-images`
- After the image has been added, open `stations.ts` and update the station object with an `image` property (take a look at other station objects for the `require` path)

## 💡 Things to keep in mind:
- The image should be `1350px` wide, so the image will look sharp on 3x PPI screens
- Please reduce the image size by using tools such as [squoosh](https://squoosh.app/)
- If you have Xcode installed, please add the assets to the Assets folder (the station images assets reside in the watch extension folder) and update the `stationsData.json` file with the image file name

## 🖼 Missing station images:
- [x] Ashkelon
- [x] Kiryat Haim
- [x] Hadera - West
- [x] Binyamina
- [x] Kiryat Hayim
- [x] Nahariya
- [x] Kiryat Gat
- [x] Kfar Habad
- [x] Haifa - HaShmona
- [x] Ramla
- [x] Rehovot
- [x] Yavne - East
- [ ] Rishon - HaRishonim
- [x] Petah Tikva - Segula
- [x] HaMifrats Central Station
- [x] Ashkelon
- [x] Dimona
- [x] Petah Tikva - Kiryat Arye
- [x] Lehavim - Rahat
- [x] Pa'ate Modi'in
- [x] Holon Junction
- [x] Bat Yam - Komemiyut
- [x] Yokne'am - Kfar Yehoshu'a
- [x] Afula R.Eitan
- [x] Beit She'an

**Comment by eithan11** [comment]
The following stations have up to date photos:

 Caesarea
 Atlit
 Kiryat Motzkin
 Bet Shemesh
 Ashdod - Ad Halom
 Sderot
 Migdal Ha'emek - Kfar Barukh
 Kiryat Malakhi

**Comment by guytepper** [comment]
@eithan11 thanks for the heads up! I've updated the list :)

**Comment by zivattias** [comment]
Hi, are photos from the internet eligible for usage in the app?

**Comment by guytepper** [comment]
Hey @zivattias :) only if their license permits it. 
you can see the bottom section of our [image attributions](https://better-rail.co.il/image-attributions/) including many photos from wikipedia

**Comment by zivattias** [comment]
Thank you for replying!
Just for clarification, Afula is checked on the missing photos list, however, it's missing in the actual live app. Is it on purpose or is it missing still?

**Comment by guytepper** [comment]
It'll be available in the app in the next version :)

**Comment by guytepper** [comment]
Apart from `Rishon - HaRishonim` station (which is under construction) - we're all set! Bravo!!
